# Generated by Django 3.2.4 on 2022-05-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_order_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="hits",
        ),
        migrations.AlterField(
            model_name="category",
            name="season",
            field=models.CharField(
                choices=[
                    ("string", "Spring"),
                    ("summer", "Summer"),
                    ("fall", "Fall"),
                    ("winter", "Winter"),
                    ("school-uniform", "Schoool uniform"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default="spring",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="product.category",
            ),
        ),
    ]
