# Generated by Django 3.2.4 on 2022-05-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_auto_20220528_1619"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="season",
            field=models.CharField(
                choices=[
                    ("spring", "Spring"),
                    ("summer", "Summer"),
                    ("fall", "Fall"),
                    ("winter", "Winter"),
                    ("school-uniform", "Schoool uniform"),
                ],
                max_length=15,
            ),
        ),
    ]
